django-app/newsfresh/classifier/urls.py
from django.urls import path
from . import views

app_name = 'classifier'

urlpatterns = [
    path('', views.index, name='index'),
    path('form/', views.form, name='form'),
    path('output/', views.output, name='output'),
]

django-app/newsfresh/newsfresh/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('classifier.urls')),
    path('admin/', admin.site.urls),
]

django-app/newsfresh/classifier/models.py
from django.db import models


# Create your models here.
class NewsInfo(models.Model):
    user_input = models.TextField(default=" ")
    news_link = models.TextField(default=" ")
    news_title = models.TextField(default=" ")
    news_text = models.TextField(default=" ")
    output = models.TextField(default=" ")
    objects = models.Manager()

django-app/newsfresh/classifier/forms.py
from django import forms


class InputForm(forms.Form):
    input_url = forms.URLField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'text', 'id': 'news_link', 'placeholder': 'Post your link'}))

django-app/newsfresh/classifier/views.py
from django.shortcuts import render
from .forms import InputForm
from newspaper import Article
from classifier.scrapper import scrape, similarity, google_search, predict
from classifier.models import NewsInfo


# Create your views here.
def index(request):
    return render(request, 'classifier/landingpage.html')


def form(request):
    form = InputForm()
    return render(request, 'classifier/form.html', {'form': form})


def output(request):
    if request.method == "POST":
        form = InputForm(request.POST)
        if form.is_valid():
            url = form.cleaned_data['input_url']
            if not NewsInfo.objects.filter(user_input=url).exists():
                article = Article(url)
                try:
                    article.download()
                except Exception as e:
                    print(e)
                    return render(request, 'classifier/error.html')
                article.parse()
                news_img = article.top_image
                article = article.text
                output, news_title, score = classify(url)
            else:
                print("news already exists")
                values = NewsInfo.objects.fiter(user_input=url)
                print(values)
                error = "Oops"
                return render(request, 'classifier/output.html', {'news_article': error})
            username = request.user.username
            if len(username) == 0:
                username = "Anonymous"
            args = {'output': output, 'news_title': news_title, 'news_article': article, 'score': score, 'news_img': news_img, 'username': username}
            return render(request, 'classifier/output.html', args)
        else:
            print(form.errors())

    else:
        print("error")
        error = "Oops"

    return render(request, 'classifier/output.html', {'url': error})


def classify(url):
    print("step-3")
    news_model = NewsInfo.objects.create()
    test_text, test_title, test_link, test_article = scrape(url)
    news_model.news_title = test_title
    news_model.news_link = test_link
    news_model.news_text = test_text
    search_urls, source_sites = google_search(test_link, test_title)
    sim_score = similarity(search_urls, test_text)
    pred_output = predict(test_text)
    if(pred_output == 1):
        output = "Unreliable"
    else:
        output = "Reliable"
    print(output)
    news_model.output = output
    news_model.save()

    return output, test_title, sim_score

django-app/newsfresh/templates/base.html
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'classifier/css/style.css' %}">
    <title>Dashboard</title>
</head>

<body>
    <div class="container-fluid">
        <div class="jumbotron jumbotron-fluid" id="jumbotron">
            <div class="d-flex justify-content-center">
                <img src="{% static 'classifier/img/prod-logo.png' %}" alt="logo">
                <h1 class="display-1 ">NewsFresh</h1>
            </div>
        </div>
        <div class="row">
            {% block col-1 %} {% endblock %} {% block col-2 %} {% endblock %}

        </div>
    </div>
























    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/js/mdb.min.js"></script>

    </script>
</body>

</html>

django-app/newsfresh/templates/classifier/error.html
{% extends 'base.html' %}{% load static %}{% block col-1 %}
<h1 class="text-center">Try another link</h1>
{% endblock %}

django-app/newsfresh/templates/classifier/form.html
{% extends 'base.html'%} {% load static %} {% block col-1 %}
<div class="col-md align-middle overflow-hidden" id="intro">
    <div class="md-form input-with-post-icon z-depth-1-half w-75 h-50 animated slideInLeft faster" id="form">
        <form action="{% url 'classifier:output' %}" method="POST">
            {% csrf_token %} {% for non_field_error in form.non_field_error %}
            <p class="help is-danger">{{ non_field_error}}</p>
            {% endfor %} {{ form }} {% for error in form.erros %}
            <p class="help is-danger">{{ error }}</p>
            {% endfor %}
            <div class="text-center">
                <button type="submit" class="btn z-depth-1-half" id="btn">Submit</button>
            </div>
        </form>
    </div>
</div>
{% endblock %} {% block col-2 %}

<div class="col-md d-flex justify-content-center" id="vector">
    <img src="{% static 'classifier/img/form.png' %}" class="animated slideInRight faster" id="png-2" alt="vector">

</div>

{% endblock %}

django-app/newsfresh/templates/classifier/info.html
{% load static %}

<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'classifier/css/style.css' %}">
    <title>Dashboard</title>
</head>

<body>
    <a href="{% url 'classifier:output' %}">
        <div class="container-fluid">
            <div class="jumbotron jumbotron-fluid" id="jumbotron">
                <div class="d-flex justify-content-center">
                    <img src="{% static 'classifier/img/prod-logo.png' %}" alt="logo">
                    <h1 class="display-1 ">NewsFresh</h1>
                </div>
            </div>
            <div class="row">

                <!-- Card Group-->

                <div class="col" id="card-group">
                    <div class="col-md align-middle overflow-hidden">
                        <!-- Card -->
                        <div class="card z-depth-1-half w-75" id="article">
                            <!-- Card content -->
                            <div class="mask flex-center rgba-white-strong">
                                <div class="card-body">
                                    <!-- Title -->
                                    <h4 class="card-title font-weight-bold">News title</h4>
                                    <hr>
                                    <!-- Text -->
                                    <p class="card-text">
                                        {{ pred_output }}
                                    </p>
                                </div>
                            </div>

                            <!-- Card footer -->
                            <div class="rounded-bottom mdb-color #0071bc text-center pt-3" id="card-footer">
                                <ul class="list-unstyled list-inline font-medium">
                                    <li class="list-inline-item pr-2 white-text"><i class="fas fa-user px-1"></i>Username</li>
                                    <li class="list-inline-item pr-2 white-text"><i class="far fa-check-circle px-1"></i>76.00%</li>
                                    <li class="list-inline-item"><a href="#" class="white-text"><i class="fas fa-link px-1"> </i></a></li>
                                    <li class="list-inline-item pr-2 white-text"><i class="fas fa-thumbs-up px-1"></i></li>
                                    <li class="list-inline-item pr-2 white-text"><i class="fas fa-thumbs-down px-1"></i></li>
                                </ul>
                            </div>
                        </div>
                        <!-- Card -->
                    </div>
                </div>

                <!-- Card group-->

                <div class="col-md d-flex justify-content-profile">

                    <div class="card testimonial-card w-75 " id="profile">

                        <!-- Background color -->
                        <!---  <div class="card-up " id="profile"></div> -->

                        <!-- Avatar -->
                        <div class="avatar mx-auto " id="avtar">
                            <img src="{% static 'classifier/img/default.png' %}" class="rounded-circle" alt="avatar" id="profile-pic">
                        </div>

                        <!-- Content -->
                        <div class="card-body">
                            <h3 class="card-title d-flex justify-content-center">Username</h3>
                            <hr>
                            <div class="d-flex justify-content-center">
                                <a type="button" class="btn-floating btn-medium  p-1 mx-3 z-depth-1  rounded-circle white"><i class="fas fa-grin-beam fa-2x green-text"></i></a>

                                <a type="button" class="btn-floating btn-medium  p-1 mx-3 z-depth-1 rounded-circle white"><i class="fas fa-angry fa-2x red-text"></i></a>

                                <a type="button" class="btn-floating btn-medium  p-1 mx-3 z-depth-1 rounded-circle white"><i class="fas fa-comment fa-2x black-text"></i></a>



                                <a type="button" class="btn-floating btn-medium  p-1 mx-3 z-depth-1 rounded-circle white"><i class="fas fa-plus-circle fa-2x blue-text"></i></a>



                            </div>

                        </div>
                        <!-- Card -->


                        <!-- Card -->

                    </div>

                </div>

            </div>
        </div>
    </a>


























    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/js/mdb.min.js"></script>
    <script type="text/javascript" src="{% static 'classifier/js/script.js' %}"></script>

</body>


</html>

django-app/newsfresh/templates/classifier/landingpage.html
{% extends 'base.html' %} {% load static %} {% block col-1 %}
<div class="col-md align-middle overflow-hidden" id="intro">
    <div id="info">
        <h2>Rate your news!</h2>
        <p>NewsFresh is just like Rotten Tomatoes for news!Users can read, rate, post news & also, keep themselves aware of fake news</p>
        <div class="text-center">
            <a href="{% url 'classifier:form' %}" type="button" class="btn z-depth-1-half animated bounce" id="btn">Try!</a>
        </div>
    </div>

</div>
{% endblock %} {% block col-2 %}

<div class="col-md d-flex justify-content-end" id="vector">
    <img src="{% static 'classifier/img/man.png' %}" id="png" class="animated bounceInRight" alt="vector">

</div>

{% endblock %}

django-app/newsfresh/templates/classifier/output.html
{% extends 'base.html'%} {% load static %} {% block col-1 %}
<div class="col-md d-flex justify-content-center">
    <div class="card z-depth-1-half w-75 animated bounceInDown" style="background-image: url({{ news_img }})" id="article">
        <!-- Card content -->
        <div class="mask flex-center rgba-white-strong">
            <div class="card-body">
                <!-- Title -->
                <h4 class="card-title font-weight-bold">{{ news_title }}</h4>
                <hr>
                <!-- Text -->
                <p class="card-text">
                    {{ news_article|truncatechars:420 }}
                </p>
            </div>
        </div>

        <!-- Card footer -->
        <div class="rounded-bottom  text-center pt-3" id="card-footer">
            <ul class="list-unstyled list-inline font-medium">
                <li class="h6 list-inline-item pr-2 white-text font-weight-bold">{{ output }}</li>
                <li class="h6 list-inline-item pr-2 white-text font-weight-bold"><i class="far fa-check-circle px-1"></i>{{ score }}</li>
            </ul>
        </div>
    </div>
</div>
{% endblock %} {% block col-2 %}
<div class="col-md d-flex justify-content-center h-50 ">

    <div class="card testimonial-card w-50 z-depth-1-half class animated bounceInUp" id="profile">

        <!-- Background color -->
        <!---  <div class="card-up " id="profile"></div> -->

        <!-- Avatar -->
        <div class="avatar mx-auto d-flex justify-content-center" id="avtar">
            <img src="{% static 'classifier/img/default.png' %}" class="rounded-circle" alt="avatar" id="profile-pic">
        </div>

        <!-- Content -->
        <div class="card-body">
            <h3 class="card-title d-flex justify-content-center">{{ username }}</h3>
            <hr>
            <div class="d-flex justify-content-center">
                <a type="button" class="btn-floating btn-medium  p-1 mx-3 z-depth-1  rounded-circle white"><i class="fas fa-grin-beam fa-2x green-text"></i></a>

                <a type="button" class="btn-floating btn-medium  p-1 mx-3 z-depth-1 rounded-circle white"><i class="fas fa-angry fa-2x red-text"></i></a>

                <a type="button" href="{% url 'classifier:form' %}" class="btn-floating btn-medium  p-1 mx-3 z-depth-1 rounded-circle white"><i class="fas fa-plus-circle fa-2x blue-text"></i></a>

            </div>

        </div>

    </div>

</div>

{% endblock %}